newmodel/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'welcome/index'
  #root 'welcome#index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :people
end

newmodel/app/models/person.rb
class Person < ApplicationRecord
  def full_name
    [first_name,last_name].join(' ')#我们在Person中有一个full_name方法
  end  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
end



#Add fields in people:
# rails g migration add_column_to_person gender:string mobile:integer address:string
# 更新值
# user5 = Person.find_by(id: '5')
# user5.update(gender: 'Female', mobile: '+12019988776', address: 'Henan')
# 添加验证代码在model里

#   validates :first_name,
#             :presence => true
#             length: { minimum: 5}

#   validates :last_name,
#             :presence => true
#             length: { minimum: 2}
# 添加controller和views

newmodel/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable   
 
end

newmodel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

newmodel/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

newmodel/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  #before_action :authenticate_user!
    def index
      @people = Person.all
    end

    def show
      @person = Person.find(params[:id])
    end
  
    def new
      @person = Person.new
    end
 
    
    def edit
      @person = Person.find(params[:id])
    end

    def create
        @person = Person.new(person_params)
        
        if @person.save 
          redirect_to @person
        else
          render 'new'
        end
    end

    def update
      @person = Person.find(params[:id])
     
      if @person.update(person_params)
        redirect_to @person
      else
        render 'edit'
      end
    end

    def destroy
      @person = Person.find(params[:id])
      @person.destroy
     
      redirect_to people_path
    end

    private
      def person_params
        params.require(:person).permit(:first_name, :last_name, :gender)
      end
end

newmodel/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

newmodel/app/helpers/home_helper.rb
module HomeHelper
end

newmodel/app/helpers/person_helper.rb
module PersonHelper
end

newmodel/app/helpers/welcome_helper.rb
module WelcomeHelper
end

newmodel/app/views/home/index.html.erb
<h1>Home#index</h1>
<%= link_to 'Name form', controller: 'people' %>

newmodel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newmodel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">

    <% if current_user %>

      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
   </p>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

newmodel/app/views/people/_form.html.erb
<%= form_for @person do |f| %>
 
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this person from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
 
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

newmodel/app/views/people/edit.html.erb
<h1>Person form</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', people_path %>

newmodel/app/views/people/index.html.erb
<h1>Listing test</h1>
<%= link_to 'Person form', new_person_path %>
<table>
  <tr>
    <th>first name</th>
    <th>last name</th>
    <th>gender</th>
  </tr>
 
  <% @people.each do |person| %>
    <tr>
      <td><%= person.first_name %></td>
      <td><%= person.last_name %></td>
      <td><%= person.gender %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Destroy', person_path(person),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

newmodel/app/views/people/new.html.erb
<h1>Person form</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', people_path %>

newmodel/app/views/people/show.html.erb
<h1>A new person</h1>
<p>
  <strong>first name:</strong>
  <%= @person.first_name %>
</p>
 
<p>
  <strong>last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>gender:</strong>
  <%= @person.gender %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> 
<%= link_to 'Back', people_path %>

newmodel/app/views/welcome/index.html.erb
<h1>Hello, This is Rails!</h1>
<% if user_signed_in? %>
<%= link_to 'Name form', controller: 'people' %>
<% end %>